app = "multilingual-chat"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  FLET_SERVER_PORT = "8000"
  FLET_SESSION_TIMEOUT = "3600"  # 1시간

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  [http_service.concurrency]
    type = "connections"
    soft_limit = 200
    hard_limit = 250